### ISSUE TITLE
Missing .env file

### ISSUE THREAD

**Issue by helios-ventures** [mayerbalintdev/GYM-One#1]
Could you provide a .env file for the project

**Comment by mayerbalintdev** [comment]
The GYM One _installer is currently not able_ to automatically specify the **.env** file, as it is created during installation. In addition, we would like to inform you that the project is **not yet** officially available and therefore it is not possible to use the software at this time.

If you would like to test the software, we welcome you to our **[Discord](https://discord.gg/h5GSPtKPdc)** channel! Sign up with us and join the testing process.

`BALINT Mayer - Center@gymoneglobal.com`
