### ISSUE TITLE
Database naming error

### ISSUE THREAD

**Issue by helios-ventures** [mayerbalintdev/GYM-One#3]
The installation instructions are to create a database with the name; 'gym_one' but the .sql file in the  SQL file creates a database with the name; 'gymone'.

Kindly update the code to reflect this.

**Comment by mayerbalintdev** [comment]
The issue has been resolved! From now on, the installer will automatically create the SQL tables in the database you specify. The documentation has also been updated, so we recommend using the installer moving forward. The installer has not been released yet! If you would like to test it, please feel free to contact me at center@gymoneglobal.com. Thank you for pointing out the issue!
